import pytest

from src.enums import StandardDirection, StandardTerrain
from src.game import StandardGame
from src.information import LeastTerrainInfo, RangeInfo, SingleInfo


@pytest.fixture(scope="function")
def game():
    return StandardGame()


def test_game_init(game: StandardGame):
    assert game._board.players == ("A", "B", "C", "D", "E", "Public", "Loot")


def test_game_demo(game: StandardGame):
    game._info.extend(
        [
            # Public Info
            SingleInfo(player="Public", name="5B", present=True),
            SingleInfo(player="Public", name="7M", present=True),
            # Least Terrain
            LeastTerrainInfo(player="E", terrain="F"),
            # Range Info
            RangeInfo(player="A", terrain="M", start=1, end=5, amount=4),
            RangeInfo(player="B", terrain="F", start=1, end=5, amount=4),
            RangeInfo(player="C", terrain="A", start=1, end=5, amount=4),
            RangeInfo(player="D", terrain="A", start=5, end=1, amount=4),
            RangeInfo(player="D", terrain="F", start=3, end=7, amount=2),
            RangeInfo(player="D", terrain="M", start=3, end=7, amount=2),
            RangeInfo(player="E", terrain="A", start=5, end=1, amount=4),
            RangeInfo(player="E", terrain="B", start=5, end=5, amount=3),
        ]
    )
    game.solve()
    assert game.get_result() == {
        ("A", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("A", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("A", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 1.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 1.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 1.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 1.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("A", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("B", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("B", StandardTerrain.FOREST, StandardDirection.NORTH): 1.0,
        ("B", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 1.0,
        ("B", StandardTerrain.FOREST, StandardDirection.EAST): 1.0,
        ("B", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 1.0,
        ("B", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("B", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("B", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("B", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("B", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
        ("C", StandardTerrain.BEACH, StandardDirection.NORTH): 1.0,
        ("C", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 1.0,
        ("C", StandardTerrain.BEACH, StandardDirection.EAST): 1.0,
        ("C", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 1.0,
        ("C", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("C", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("C", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("C", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("C", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("C", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("D", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.SOUTH): 1.0,
        ("D", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 1.0,
        ("D", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("D", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 1.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 1.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("D", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("E", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 1.0,
        ("E", StandardTerrain.BEACH, StandardDirection.WEST): 1.0,
        ("E", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 1.0,
        ("E", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("E", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("E", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 1.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.SOUTH): 1.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("Public", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.WEST): 0.0,
        ("Public", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 1.0,
        ("Public", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.NORTH): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.NORTHEAST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.EAST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.SOUTHEAST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.SOUTH): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.SOUTHWEST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.WEST): 0.0,
        ("Loot", StandardTerrain.BEACH, StandardDirection.NORTHWEST): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.NORTH): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.NORTHEAST): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.EAST): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.SOUTHEAST): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.SOUTH): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.SOUTHWEST): 0.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.WEST): 1.0,
        ("Loot", StandardTerrain.FOREST, StandardDirection.NORTHWEST): 1.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.NORTH): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.NORTHEAST): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.EAST): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHEAST): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.SOUTH): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.SOUTHWEST): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.WEST): 0.0,
        ("Loot", StandardTerrain.MOUNTAIN, StandardDirection.NORTHWEST): 0.0,
    }
